name: Build workflow2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven -B -ntp Clean Verify
        run: mvn clean verify
        working-directory: ./java-springboot-full-stack-ci-cd-with-github-action