#name: Deploy workflow
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#    env:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 21
#          cache: maven
#
#      - name: Generate Build Number
#        run: |
#          BUILD_NUMBER=$(date +'%Y%m%d%H%M%S')
#          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
#          echo "Generated Build Number: $BUILD_NUMBER"
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ env.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build & Push Image with Jib
#        working-directory: backend   # ✅ where pom.xml exists
#        run: |
#          mvn -B -ntp clean verify jib:build \
#            -Djib.to.tags=${BUILD_NUMBER}

name: Deploy workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Generate Build Number
        run: |
          BUILD_NUMBER=$(date +'%Y%m%d%H%M%S')
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Build & Push Image with Jib
        working-directory: backend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          mvn -B -ntp clean verify jib:build \
            -DskipTests 
            -Djib.to.auth.username=$DOCKER_USERNAME \
            -Djib.to.auth.password=$DOCKER_PASSWORD \
            -Ddocker.image.tag=${BUILD_NUMBER}
